### ISSUE TITLE
AttributeError: module 'pip._internal' has no attribute 'commands'

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/python#97]
```
Traceback (most recent call last):
  File "/usr/src/app/entrypoint.py", line 10, in <module>
    output['manifests'][manifest.filename] = { 'current': { 'dependencies': manifest.dio_dependencies() } }
  File "/usr/src/app/models.py", line 89, in dio_dependencies
    'available': [{'name': x} for x in get_available_versions_for_dependency(dep.key, dep.specs)],
  File "/usr/src/app/models.py", line 167, in get_available_versions_for_dependency
    list_command = pip._internal.commands.ListCommand()
AttributeError: module 'pip._internal' has no attribute 'commands'
```

Relevant jobs:
https://app.dependencies.io/j/6dcf901c-040f-4b9a-8ec8-d795c7862af3
https://app.dependencies.io/j/128f5e6d-b025-4d6c-821d-0b4cefaa3f1d

This is a result of https://github.com/pypa/pip/commit/09fd200c599de4fadf2ff814a1bef855bc6d77e8#diff-77c4d7f6b635899eff3a6367e595a0c8 that was just released as part of [pip 19.3](https://github.com/pypa/pip/releases/tag/19.3), where `pip._internal.commands` is no longer imported in `pip._internal`'s `__init__.py`.

This is further complicated by https://github.com/pypa/pip/commit/1f09e67f342037fb2ae38ef5a82d232ef9116880#diff-25a31740fea4e0eefa38ee5b171d9c3d removing the `ListCommand` import `from pip._internal.commands.list` in `pip._internal.commands`'s `__init__.py` and `ListCommand` itself being changed to subclass a new and different `IndexGroupCommand` class with https://github.com/pypa/pip/commit/e74fd24c71de688d5b93e426c2f4961a4de2ccd0#diff-11a93d0cc9ae5ef29d0124a9f3775d2f.

**Comment by davegaeddert** [comment]
Hey @Harmon758, thanks for the detail. I did get a failing build yesterday but haven't had a chance to look yet. Would you be up for trying the new version of dependencies.io? It is out now and the Python support no longer uses this internal pip stuff ;)

Basically all effort is going towards the new version now (v3) and I've been reaching out to v2 customers to help them migrate -- you're on that list! https://docs.dependencies.io

What do you think?

**Comment by Harmon758** [comment]
Sorry, but I'm not really looking to handle dependency updates by running anything locally or via separate CI. I understand the new direction, but unfortunately, it's just not something I'm interesting in using right now. I'm assuming this means v2 will be deprecated and/or shut down at some point as well?

**Comment by davegaeddert** [comment]
No problem. Running it locally is just for testing/debugging but it would require you have CI to actually get updates.

Yes, it does mean v2 will be shut down at some point ideally but I don't have any concrete dates on that yet. There are some paying customers that need to be migrated first.
